- hosts: master
  remote_user: root
  tasks:
      # Initialization
      - name: disable selinux
        selinux: state=permissive policy=targeted

      - name: install Java
        yum: name=java-1.8.0-openjdk

      - name: install EPEL
        yum: name=epel-release

      - name: install supervisord
        yum: name=supervisor

      - name: install bzip2
        yum: name=bzip2

      - name: install httpd
        yum: name=httpd

      - name: create runtime user
        user: name=runtime shell=/bin/bash

      - name: create runtime dir
        file: path=/home/runtime/run/ state=directory owner=runtime group=runtime recurse=yes

      # install ELK stack
      - name: install elasticsearch rpm key
        rpm_key: state=present key=https://packages.elastic.co/GPG-KEY-elasticsearch

      - name: install elasticsearch 2.x repository
        copy: src=config/elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo owner=root group=root

      - name: install elasticsearch
        yum: name=elasticsearch

      - name: download kibana
        get_url: url=https://download.elastic.co/kibana/kibana/kibana-4.2.0-linux-x64.tar.gz dest=/root/kibana-4.2.0-linux-x64.tar.gz validate_certs=no force=no

      - name: extract kibana
        unarchive: src=/root/kibana-4.2.0-linux-x64.tar.gz dest=/opt/ copy=no creates=/opt/kibana-4.2.0-linux-x64/

      - name: change ownership of kibana dir
        file: path=/opt/kibana-4.2.0-linux-x64/ state=directory owner=root group=root recurse=yes

      - name: ensure all directory in kibana dir can be opened by all
        command: find /opt/kibana-4.2.0-linux-x64/ -type d -exec chmod og+rx '{}' ';'

      - name: ensure all files in kibana dir can be opened by all
        command: find /opt/kibana-4.2.0-linux-x64/ -type f -exec chmod og+r '{}' ';'

      - name: configure kibana
        copy: src=config/kibana.yml dest=/opt/kibana-4.2.0-linux-x64/config/kibana.yml owner=root group=root

      - name: create kibana supervisord config
        copy: src=config/supervisord.ini dest=/etc/supervisord.d/kibana.ini owner=root group=root

      - name: start supervisord on boot
        service: name=supervisord state=restarted enabled=yes

      - name: start elasticsearch on boot
        service: name=elasticsearch state=restarted enabled=yes

      - name: open firewall port 5601
        firewalld: port=5601/tcp permanent=true state=enabled immediate=yes


